# Update these values for your local PostgreSQL instance.
db.url=jdbc:postgresql://localhost:5432/pc_warehouse
db.username=app
db.password=a
db.schema=app
db.flyway.enabled=true
db.flyway.locations=classpath:db/migration
